export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";

export const LOADING_DOCTORS = "LOADING_DOCTORS";
export const ERROR_DOCTORS = "ERROR_DOCTORS";
export const GET_DOCTORS = "GET_DOCTORS";
export const ADD_DOCTORS = "ADD_DOCTORS";
export const DELETE_DOCTORS = "DELETE_DOCTORS";
export const UPDATE_DOCTORS = "UPDATE_DOCTORS";

export const GET_MEDICINE = "GET_MEDICINE";
export const ADD_MEDICINE = "ADD_MEDICINE";
export const DELETE_MEDICINE = "DELETE_MEDICINE";
export const UPDATE_MEDICINE = "UPDATE_MEDICINE";

export const ADD_TO_CART = "ADD_TO_CART";
export const INC_QTY = "INC_QTY";
export const DEC_QTY = "DEC_QTY";
export const REMOVE_ITEM = "REMOVE_ITEM";

export const FAVORITE_ITEM = "FAVORITE_ITEM";

export const GET_DEPARTMENT_DATA = "GET_DEPARTMENT_DATA";
export const ADD_DEPARTMENT_DATA = "ADD_DEPARTMENT_DATA";
export const DELETE_DEPARTMENT_DATA = "DELETE_DEPARTMENT_DATA";
export const UPDATE_DEPARTMENT_DATA = "UPDATE_DEPARTMENT_DATA";



